server:
  port: 8080  # 网关对外暴露 8080 端口

spring:
  application:
    name: petstore-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启基于服务名的默认路由，便于测试
      routes:
        # --- 路由配置 1：转发到用户服务 ---
        - id: user-route                # 路由 ID，保持唯一
          uri: lb://MyPetStore-UserService  # 目标地址。lb:// 代表 LoadBalancer，后面跟 Nacos 中的服务名
          predicates:
            - Path=/api/user/** # 断言：如果请求路径以 /api/user/ 开头，就转发给用户服务

        # --- 路由配置 2：转发到商品服务 ---
        - id: catalog-route
          uri: lb://petstore-catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=1