server:
  port: 8080  # 网关对外暴露 8080 端口

spring:
  application:
    name: petstore-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 地址
    gateway:
      discovery:
        locator:
          enabled: true # 开启基于服务名的默认路由，便于测试
      routes:
        # --- 路由配置 1：转发到用户服务 ---
        - id: user-route                # 路由 ID，保持唯一
          uri: lb://MyPetStore-UserService  # 目标地址。lb:// 代表 LoadBalancer，后面跟 Nacos 中的服务名
          predicates:
            - Path=/api/v1/user/** # 断言：如果请求路径以 /api/v1/user/ 开头，就转发给用户服务
          filters:
            - RewritePath=/api/v1/user/(?<segment>.*), /api/v1/$\{segment} # 对请求路径进行重写

        # --- 路由配置 2：转发到商品服务 ---
        - id: product-route
          uri: lb://MyPetStore-ProductService
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=0

        # --- 路由配置 3：转发到订单服务 ---
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/api/v1/orders/(?<segment>.*), /api/order/$\{segment} # 对请求路径进行重写
  # 配置日志级别
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    # 如果需要更详细的信息，可以添加以下配置
    # org.springframework.web.reactive: DEBUG